from pathlib import Path
import json,html
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'library-catalog.json').read_text())
h=lambda s: html.escape(s,quote=True)
books='\n'.join(f'''<article class="book"><button class="cover-button" type="button" data-pdf="{h(b['pdf'])}" data-title="{h(b['title'])}" data-locked="{str(b['locked']).lower()}" aria-label="Read {h(b['title'])}"><img src="{h(b['cover'])}" alt="" loading="lazy"></button><h3>{h(b['title'])}</h3><p>{'Continue in the original Library to keep the reading sequence.' if b['locked'] else 'Open the book and turn its pages.'}</p></article>''' for b in data['books'])
software='\n'.join(f'''<article class="disc-entry"><img class="case-art" src="library-assets/dvd-{h(s['id'])}.jpg" alt="{h(s['title'])} CD case" loading="lazy"><div class="disc-copy"><img class="disc-art" src="library-assets/disc-{h(s['id'])}.jpg" alt="" loading="lazy"><h3>{h(s['title'])}</h3><p>{h(s['description'])}</p><div class="actions"><a href="{h(s['source'])}" target="_blank" rel="noopener noreferrer">Source on GitHub</a>{''.join(f'<a href="{h(x["url"])}" target="_blank" rel="noopener noreferrer">{h(x["title"])}</a>' for x in s['launches'])}</div></div></article>''' for s in data['software'])
projects='\n'.join(f'''<a class="project" href="{h(p['url'])}" {'target="_blank" rel="noopener noreferrer"' if p['url'].startswith('https:') else ''}><strong>{h(p['title'])}</strong><span>{h(p['description'])}</span></a>''' for p in data['projects'])
(root/'library.html').write_text(f'''<!doctype html>
<!-- Prepared by: Codex. GitHub Pages collection for Spirit Striker. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Library | Spirit Striker</title><link rel="stylesheet" href="library.css?v=1"><script src="library.js?v=1" defer></script></head>
<body><header class="mast"><a class="back" href="menu.html" id="back-menu">← Main menu</a><div class="identity"><span class="small">Spirit Striker / Terrace World</span><h1>Library</h1><p>Books, recovered software, and working maps of the world.</p></div><nav class="sections" aria-label="Library sections"><a href="#books" data-section="books">Books <span>{len(data['books'])}</span></a><a href="#software" data-section="software">Software <span>{len(data['software'])}</span></a><a href="#world" data-section="world">World &amp; planners</a></nav></header>
<main><section id="books" class="collection" aria-labelledby="books-title"><div class="section-heading"><h2 id="books-title">The books</h2><p>Original covers. Published books open in the working page reader.</p></div><div class="book-grid">{books}</div></section>
<section id="software" class="collection" aria-labelledby="software-title"><div class="section-heading"><h2 id="software-title">Recovered software</h2><p>CD cases and discs from the original collection. Source links point to the public repositories; web tools open where available.</p></div><div class="disc-list">{software}</div></section>
<section id="world" class="collection" aria-labelledby="world-title"><div class="section-heading"><h2 id="world-title">World &amp; planners</h2><p>The live routes behind this collection.</p></div><div class="project-list">{projects}</div></section></main>
<div id="reader" class="reader" hidden><div class="reader-bar"><button type="button" id="close-reader">← Library</button><strong id="reader-title"></strong><a id="external-reader" href="https://spiritstriker.app/library.html" target="_blank" rel="noopener noreferrer">Open full page</a></div><iframe id="book-frame" title="Book reader" src="about:blank" allow="fullscreen"></iframe></div>
</body></html>''')
